=== raml-apis/23andMe/schemas/placeorderRequest-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "first_name" : {
      "type" : "string" ,
      "required" : true
    } ,
    "last_name" : {
      "type" : "string" ,
      "required" : true
    } ,
    "address_line1" : {
      "type" : "string" ,
      "required" : true
    } ,
    "city" : {
      "type" : "string" ,
      "required" : true
    } ,
    "state" : {
      "type" : "string" ,
      "required" : false
    } ,
    "country" : {
      "type" : "string" ,
      "required" : true
    } ,
    "email" : {
      "type" : "string" ,
      "required" : true
    } ,
    "phone" : {
      "type" : "string" ,
      "required" : true
    } ,
    "shipping_method" : {
      "type" : "string" ,
      "required" : true
    } ,
    "product_id" : {
      "type" : "string" ,
      "required" : true
    } ,
    "postal_code" : {
      "type" : "string" ,
      "required" : false
    } ,
    "personalizations" : {
      "type" : "array" ,
      "required" : true ,
      "items" : [
        {
          "type" : "string"
        }
      ]
    }
  }
}

=== raml-apis/23andMe/examples/placeorderRequest-example.json
{
  "first_name" : "Barack" ,
  "last_name" : "Obama" ,
  "address_line1" : "1600 Pennsylvania Avenue" ,
  "city" : "Washington" ,
  "state" : "DC" ,
  "country" : "US" ,
  "email" : "test@example.com" ,
  "phone" : "12123644576" ,
  "shipping_method" : "Standard" ,
  "product_id" : "product_id" ,
  "postal_code" : "20500" ,
  "personalizations" : [
    "Barack" ,
    "Michelle"
  ]
}
